graduate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='root.html'), name='root'),
    path('users/', include('users.urls')),
    path('', include('selling.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

selling/urls.py
from django.urls import path
from . import views

app_name = 'selling'

urlpatterns = [
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup')
]

selling/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="selling/post/%Y/%m/%d")
    caption = models.CharField(max_length=300)
    location = models.CharField(max_length=100)
    price = models.CharField(max_length=20)

    def __str__(self):
        return self.caption

    def get_absolute_url(self):
        return reverse("selling:post_detail", args=[self.pk])

users/models.py
from django.conf import settings
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.template.loader import render_to_string


class UserManager(BaseUserManager):
    def create_user(self, user_id, password, nick_name, email, student_num, date_joined):
        if not email:
            raise ValueError('이메일은 필수입니다.')

        user = self.model(
            user_id = user_id,
            nick_name = nick_name,
            email = email,
            student_num = student_num,
            date_joined = date_joined,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password, nick_name=None, email=None, student_num=None, date_joined=None):
        user = self.create_user(user_id, password, nick_name, email, student_num, date_joined)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    user_id = models.CharField(max_length=18 , verbose_name='아이디', unique=True)
    nick_name = models.CharField(max_length=10, verbose_name='닉네임', unique=True, null=True)
    email = models.EmailField(verbose_name='이메일', max_length=128, unique=True, null=True)
    student_num = models.IntegerField(verbose_name='학번', null=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일자', null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['email']

    def send_email(self):
        title = render_to_string("users/send_email_title.txt", {
            "user" : self,
        })
        content = render_to_string("users/send_email_content.txt", {
            "user" : self,
        })
        sender_email = settings.EMAIL_SENDER
        send_mail(title, content, sender_email, [self.email], fail_silently=False)

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

selling/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["photo", "caption", "location", "price"]
        widgets = {
            "caption": forms.Textarea,
        }

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignUpForm(UserCreationForm):
    #회원가입 폼 필수 필드 지정
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_id'].required = True
        self.fields['nick_name'].required = True
        self.fields['email'].required = True
        self.fields['student_num'].required = True

    class Meta(UserCreationForm):
        model = User
        fields = ['user_id', 'nick_name', 'email', 'student_num']

selling/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PostForm
from .models import Post


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, "포스팅을 저장했습니다")
            return redirect("/")
    else:
        form = PostForm()

    return render(request, "selling/post_form.html",{
        "form": form,
    })

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, "selling/post_detail.html",{
        "post": post,
    })

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth.views import LoginView, logout_then_login


login = LoginView.as_view(template_name="users/login_form.html")
def logout(request):
    return logout_then_login(request)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            signed_user = form.save()
            messages.success(request, "회원가입을 환영합니다")
            signed_user.send_email()
            return redirect("/")
    else:
        form = SignUpForm()
    return render(request, 'users/signup_form.html',{
        'form': form,
    })

graduate/templates/form.html
{% load bootstrap4 %}
<div class="card">
  {% if form_title %}
    <div class="card-header">
        {{ form_title }}
    </div>
  {% endif %}
  <div class="card-body">
    <form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
  <button type="submit" class="btn btn-primary">{{ submit_label|default:"Submit" }}</button>
  {% endbuttons %}
</form>

  </div>
</div>

graduate/templates/layout.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>졸업생 중고 장터</title>
    <link rel="stylesheet" href="{% static "bootstrap-5.2.3-dist/css/bootstrap.min.css" %}"/>
    <script src="{% static "jquery.min.js" %}"></script>
    <script src="{% static "bootstrap-5.2.3-dist/js/bootstrap.min.js" %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

  </head>
  <body>
    <header>
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-basket2" viewBox="0 0 16 16">
              <path d="M4 10a1 1 0 0 1 2 0v2a1 1 0 0 1-2 0v-2zm3 0a1 1 0 0 1 2 0v2a1 1 0 0 1-2 0v-2zm3 0a1 1 0 1 1 2 0v2a1 1 0 0 1-2 0v-2z"/>
              <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-.623l-1.844 6.456a.75.75 0 0 1-.722.544H3.69a.75.75 0 0 1-.722-.544L1.123 8H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM2.163 8l1.714 6h8.246l1.714-6H2.163z"/>
            </svg>
            <div style="margin-left: 1rem;">
              졸업생 중고 장터
            </div>
          </a>

          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        
            <li><a href="#" class="nav-link px-2 link-dark">거래 게시판</a></li>
            <li><a href="#" class="nav-link px-2 link-dark">유저 페이지</a></li>
            <li><a href="#" class="nav-link px-2 link-dark">로그인/로그아웃</a></li>
          </ul>
        </div>
      </div>

    </header>
    <div class="container">
      {% block content %} {% endblock %}
    </div>
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Company, Inc</p>
  </footer>
  </body>
</html>

graduate/templates/root.html
{% extends "layout.html" %} {% block content %}
<hr/>
<a href="{% url "selling:post_new" %}" class="btn btn-primary">새 글 쓰기</a>

{% endblock %}

selling/templates/selling/layout.html
{% extends "layout.html" %}

selling/templates/selling/post_detail.html
{% extends "selling/layout.html" %}

{% block content %}
    <div class="container text-center">
  <div class="row">
    <div class="col">
      <div class="card shadow-sm">
        <svg
          class="bd-placeholder-img card-img-top"
          width="100%"
          height="225"
          xmlns="http://www.w3.org/2000/svg"
          role="img"
          aria-label="Placeholder: 예비이미지"
          preserveAspectRatio="xMidYMid slice"
          focusable="false"
        >
          <title>예비이미지</title>
          <rect width="100%" height="100%" fill="#55595c"></rect>
          <text x="50%" y="50%" fill="#eceeef" dy=".3em">예비이미지</text>
        </svg>

        <div class="card-body">
            <div>
                {{ post.author }}
            </div>
          <p class="card-text">글 제목</p>
          <div class="d-flex justify-content-between align-items-center">
            <button type="button" class="btn btn-sm btn-outline-secondary">
              자세히 보기
            </button>

            <small class="text-muted">9 분전</small>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
  </div>
</div>
{% endblock %}

selling/templates/selling/post_form.html
{% extends "selling/layout.html" %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">{% include "form.html" with form_title="새 글 쓰기" submit_label="새 글 쓰기" %}</div>
  </div>
</div>
{% endblock %}

users/templates/users/layout.html
{% extends "layout.html" %}

users/templates/users/login_form.html
{% extends "users/layout.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      {% include "form.html" with form_title="로그인" submit_label="로그인" %}
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/signup_form.html
{% extends "users/layout.html" %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">{% include "form.html" with form_title="회원가입" submit_label="회원가입" %}</div>
  </div>
</div>
{% endblock %}